### ISSUE TITLE
Investigate whether Build Summary works for index page

### ISSUE THREAD

**Issue by leo** [zeit/integrations#25]
[Dariel Noel](https://twitter.com/dariel_noel) reported that, if the Build Summary integration is used for a simple Next.js site with `pages/index.js` and `pages/about.js` – only editing `pages/about.js` will trigger a Build Summary.

We need to investigate whether that's correct and potentially fix the problem.

**Comment by lucleray** [comment]
> only editing pages/about.js will trigger a Build Summary

That's expected. I'm not sure I understand the issue here.

**Comment by leo** [comment]
@lucleray Even that editing `pages/index.js` does nothing?

Hence "only":

> only editing pages/about.js will trigger a Build Summary

**Comment by lucleray** [comment]
Got it! Unfortunately I can't reproduce ([tried here](https://github.com/lucleray/luc.im/pull/23)). Is the repository public?

**Comment by leo** [comment]
Invited you to a DM group.

**Comment by leo** [comment]
Closing in favor of https://github.com/zeit/api/issues/827
