### ISSUE TITLE
Hover effect on buttons wrong

### ISSUE THREAD

**Issue by leo** [zeit/integrations#30]
Please use the hover effect that we're using for all dark buttons on zeit.co! As you can see, it currently has a blue underlining:

![image](https://user-images.githubusercontent.com/6170607/64251943-ef740180-cf19-11e9-9994-9e794805b520.png)

**Comment by lucleray** [comment]
@leo This requires changes in the available components for integrations.

I suggest adding a way to deactivate styling of links:
```jsx
<Link href="https://google.com" unstyled><Button>Connect To GitHub</Button></Link>
```

**Comment by leo** [comment]
It should work just like on front, where button components don't have the underline.

**Comment by lucleray** [comment]
Fixed in https://github.com/zeit/integrations/pull/53.
