### ISSUE TITLE
Unable to associate a Zeit project with a GCP integration

### ISSUE THREAD

**Issue by hoodwink73** [zeit/integrations#56]
I get a broken experience when I am trying to associate a Zeit project with Google Cloud integration.

This is the screen I am redirected to after I select a Zeit project from the dropdown.

![Screenshot 2019-11-20 19 39 13](https://user-images.githubusercontent.com/1285699/69300360-f406a700-0c38-11ea-9822-3c0a524896b9.jpg)

My zeit username is `arijit` and I have connected this GitHub account with it.

**Comment by rdev** [comment]
This is now fixed 🙌🏻

**Comment by hoodwink73** [comment]
Thanks a lot. Really appreciate this.
